version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 10
    commands:
      - npm install -g @vue/cli
  build:
    commands:
      - cd static-website
      - npm install
      - npm run ci
      - cd ..
      - mvn clean package -DpackageBucket=${PACKAGE_BUCKET}
